version: "2"
services: 
 
  db:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "5883:3306"
    environment:
      MYSQL_ROOT_USER: 'your password'
      MYSQL_ROOT_PASSWORD: 'your password'
      MYSQL_DATABASE: 'your db name'
    volumes: 
      - ./my_datavolume:/var/lib/mysql
     
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8584:80"

      
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  

      