"""050919

Revision ID: 06180c1a3d84
Revises: df694b4fa28a
Create Date: 2019-09-05 17:24:54.350233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06180c1a3d84'
down_revision = 'df694b4fa28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payment_s', sa.Column('invoice_payment', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoice_payment_s', 'supplier', ['invoice_payment'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_payment_s', type_='foreignkey')
    op.drop_column('invoice_payment_s', 'invoice_payment')
    # ### end Alembic commands ###
