"""pre2

Revision ID: 0fe7a6e73e5f
Revises: 6a20eea66503
Create Date: 2019-06-18 16:32:33.975936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe7a6e73e5f'
down_revision = '6a20eea66503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_fin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llc', sa.String(length=240), nullable=True),
    sa.Column('supplier', sa.String(length=240), nullable=True),
    sa.Column('req_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('req_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_fin')
    # ### end Alembic commands ###
