"""dir

Revision ID: 112386250858
Revises: 508df6ca09c5
Create Date: 2019-07-11 16:05:25.381046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112386250858'
down_revision = '508df6ca09c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_fin', sa.Column('direction', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_fin', 'direction')
    # ### end Alembic commands ###
