"""inv

Revision ID: 131a9096dea6
Revises: c61cbf31c947
Create Date: 2019-08-12 20:01:02.951414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131a9096dea6'
down_revision = 'c61cbf31c947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoicecust', sa.Column('req_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoicecust', 'request', ['req_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoicecust', type_='foreignkey')
    op.drop_column('invoicecust', 'req_id')
    # ### end Alembic commands ###
