"""2

Revision ID: 14e625195511
Revises: 5e3ecf32efed
Create Date: 2019-07-28 12:51:20.242404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e625195511'
down_revision = '5e3ecf32efed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zayvka', sa.Column('request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'zayvka', 'request', ['request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zayvka', type_='foreignkey')
    op.drop_column('zayvka', 'request_id')
    # ### end Alembic commands ###
