"""suppre

Revision ID: 1ee0033ffbbe
Revises: 8b0207072cb7
Create Date: 2019-07-16 14:47:26.477800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee0033ffbbe'
down_revision = '8b0207072cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_fin', sa.Column('profit', sa.Integer(), nullable=True))
    op.add_column('pre_fin', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pre_fin', 'supplier', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pre_fin', type_='foreignkey')
    op.drop_column('pre_fin', 'supplier_id')
    op.drop_column('pre_fin', 'profit')
    # ### end Alembic commands ###
