"""'supp_docs'

Revision ID: 21b72027ea9a
Revises: fa07a4b138d0
Create Date: 2019-11-28 20:53:51.107766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b72027ea9a'
down_revision = 'fa07a4b138d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplierdocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice', sa.Text(), nullable=True),
    sa.Column('confirmdoc', sa.Text(), nullable=True),
    sa.Column('orderdoc', sa.Text(), nullable=True),
    sa.Column('supp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supp_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplierdocs')
    # ### end Alembic commands ###
