"""new

Revision ID: 2926acfe7a2f
Revises: 
Create Date: 2019-07-15 20:01:24.340772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2926acfe7a2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zayvka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('pre_fin', 'profit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_fin', sa.Column('profit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('zayvka')
    # ### end Alembic commands ###
