"""g

Revision ID: 292e60b94486
Revises: 
Create Date: 2019-07-10 10:47:46.296904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292e60b94486'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_sup', sa.Column('path', sa.String(length=1000), nullable=True))
    op.add_column('pre_fin', sa.Column('req_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'pre_fin', ['req_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pre_fin', type_='unique')
    op.drop_column('pre_fin', 'req_id')
    op.drop_column('new_sup', 'path')
    # ### end Alembic commands ###
