"""n

Revision ID: 2963e2857f53
Revises: 
Create Date: 2019-07-28 07:05:52.700051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2963e2857f53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prefin', sa.Column('s_inv_date_to_pay', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prefin', 's_inv_date_to_pay')
    # ### end Alembic commands ###
