"""tr

Revision ID: 2ce41f7fd958
Revises: f891e393d4da
Create Date: 2019-10-17 20:12:59.440076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce41f7fd958'
down_revision = 'f891e393d4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tr_payments', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tr_payments', 'invoice_payment_s', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tr_payments', type_='foreignkey')
    op.drop_column('tr_payments', 'payment_id')
    # ### end Alembic commands ###
