"""0809

Revision ID: 2f0452b6f250
Revises: 7760ada6c1eb
Create Date: 2019-09-08 16:46:08.239158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0452b6f250'
down_revision = '7760ada6c1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payment_s', sa.Column('commision', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_payment_s', 'commision')
    # ### end Alembic commands ###
