"""'transit'

Revision ID: 360251010cbe
Revises: 
Create Date: 2019-09-10 07:25:35.684162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '360251010cbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_payment_s', 'transit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payment_s', sa.Column('transit', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
