"""'a_user'

Revision ID: 380757f1e5a1
Revises: 87f3a965eabc
Create Date: 2019-10-06 18:48:51.193170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380757f1e5a1'
down_revision = '87f3a965eabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agreements', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agreements', type_='foreignkey')
    op.drop_column('agreements', 'user_id')
    # ### end Alembic commands ###
