"""'u'

Revision ID: 3b32c04f8f9f
Revises: 6d151ee287a3
Create Date: 2019-11-05 19:53:54.624811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b32c04f8f9f'
down_revision = '6d151ee287a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tr_payments', sa.Column('confirm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tr_payments', 'confirm')
    # ### end Alembic commands ###
