"""'innc'

Revision ID: 405dc6804a51
Revises: cbb0863c2f81
Create Date: 2019-02-21 17:41:46.722111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '405dc6804a51'
down_revision = 'cbb0863c2f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_inn', sa.Integer(), nullable=True))
    op.drop_index('inn', table_name='customer')
    op.create_unique_constraint(None, 'customer', ['customer_inn'])
    op.drop_column('customer', 'inn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('inn', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customer', type_='unique')
    op.create_index('inn', 'customer', ['inn'], unique=True)
    op.drop_column('customer', 'customer_inn')
    # ### end Alembic commands ###
