"""'Supplier_pay1'

Revision ID: 434a0a3742a1
Revises: ab636407c04c
Create Date: 2019-08-25 14:59:29.685669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '434a0a3742a1'
down_revision = 'ab636407c04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supp_payment', sa.Column('s_inv_amount', sa.Integer(), nullable=True))
    op.add_column('supp_payment', sa.Column('s_inv_currency', sa.String(length=120), nullable=True))
    op.add_column('supp_payment', sa.Column('s_inv_number', sa.String(length=120), nullable=True))
    op.add_column('supp_payment', sa.Column('s_inv_pay_day', sa.DateTime(), nullable=True))
    op.add_column('supp_payment', sa.Column('s_invoice_date', sa.DateTime(), nullable=True))
    op.add_column('supp_payment', sa.Column('s_payment_summ', sa.Integer(), nullable=True))
    op.drop_column('supp_payment', 'c_inv_currency')
    op.drop_column('supp_payment', 'c_inv_pay_day')
    op.drop_column('supp_payment', 'c_inv_number')
    op.drop_column('supp_payment', 'c_inv_amount')
    op.drop_column('supp_payment', 'c_payment_summ')
    op.drop_column('supp_payment', 'c_invoice_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supp_payment', sa.Column('c_invoice_date', mysql.DATETIME(), nullable=True))
    op.add_column('supp_payment', sa.Column('c_payment_summ', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('supp_payment', sa.Column('c_inv_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('supp_payment', sa.Column('c_inv_number', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('supp_payment', sa.Column('c_inv_pay_day', mysql.DATETIME(), nullable=True))
    op.add_column('supp_payment', sa.Column('c_inv_currency', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('supp_payment', 's_payment_summ')
    op.drop_column('supp_payment', 's_invoice_date')
    op.drop_column('supp_payment', 's_inv_pay_day')
    op.drop_column('supp_payment', 's_inv_number')
    op.drop_column('supp_payment', 's_inv_currency')
    op.drop_column('supp_payment', 's_inv_amount')
    # ### end Alembic commands ###
