"""minsale

Revision ID: 4940e4b24002
Revises: 81de08690e82
Create Date: 2019-03-25 12:56:21.955699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4940e4b24002'
down_revision = '81de08690e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('min_sale', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'min_sale')
    # ### end Alembic commands ###
