"""'3108/1'

Revision ID: 494d49516402
Revises: f47c4dbec479
Create Date: 2019-08-31 07:55:21.460785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494d49516402'
down_revision = 'f47c4dbec479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supp_payment', sa.Column('day_plan_pay', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supp_payment', 'day_plan_pay')
    # ### end Alembic commands ###
