"""ct

Revision ID: 508df6ca09c5
Revises: 545be421ea17
Create Date: 2019-07-11 11:06:26.569843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508df6ca09c5'
down_revision = '545be421ea17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('complete_fin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'complete_fin')
    # ### end Alembic commands ###
