"""invoicecust

Revision ID: 52ffcaa009f4
Revises: 360251010cbe
Create Date: 2019-09-13 18:52:44.271811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ffcaa009f4'
down_revision = '360251010cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_payment_c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summ', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('invoicecust_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoicecust_id'], ['invoicecust.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoicecust', sa.Column('invoice_amount', sa.Float(), nullable=True))
    op.add_column('invoicecust', sa.Column('invoice_date', sa.DateTime(), nullable=True))
    op.add_column('invoicecust', sa.Column('invoice_deadline_payment', sa.DateTime(), nullable=True))
    op.add_column('invoicecust', sa.Column('invoice_number', sa.Text(), nullable=True))
    op.add_column('invoicecust', sa.Column('invoice_tracking_company', sa.Text(), nullable=True))
    op.add_column('invoicecust', sa.Column('invoice_tracking_day', sa.DateTime(), nullable=True))
    op.add_column('invoicecust', sa.Column('invoice_tracking_number', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoicecust', 'invoice_tracking_number')
    op.drop_column('invoicecust', 'invoice_tracking_day')
    op.drop_column('invoicecust', 'invoice_tracking_company')
    op.drop_column('invoicecust', 'invoice_number')
    op.drop_column('invoicecust', 'invoice_deadline_payment')
    op.drop_column('invoicecust', 'invoice_date')
    op.drop_column('invoicecust', 'invoice_amount')
    op.drop_table('invoice_payment_c')
    # ### end Alembic commands ###
