"""empty message

Revision ID: 53b55c0c8042
Revises: 511b5b7a0f73
Create Date: 2019-12-23 07:39:50.460039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b55c0c8042'
down_revision = '511b5b7a0f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uid')
    # ### end Alembic commands ###
