"""t

Revision ID: 545be421ea17
Revises: 494aa600a12c
Create Date: 2019-07-11 11:05:03.784330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545be421ea17'
down_revision = '494aa600a12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('test_new', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'test_new')
    # ### end Alembic commands ###
