"""empty message

Revision ID: 5925ba94ced4
Revises: 
Create Date: 2019-12-21 09:49:19.063301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5925ba94ced4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_graph_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_graph_id')
    # ### end Alembic commands ###
