"""finance_datetime

Revision ID: 5ae73f6dbef5
Revises: 2b29f358b7ac
Create Date: 2019-06-01 08:16:32.619113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae73f6dbef5'
down_revision = '2b29f358b7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance', sa.Column('dtae', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance', 'dtae')
    # ### end Alembic commands ###
