"""req_id

Revision ID: 60d19fff565d
Revises: 9fd3235fde9d
Create Date: 2019-06-18 16:21:28.336116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d19fff565d'
down_revision = '9fd3235fde9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_fin', sa.Column('req_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'pre_fin', ['req_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pre_fin', type_='unique')
    op.drop_column('pre_fin', 'req_id')
    # ### end Alembic commands ###
