"""g1

Revision ID: 6393181f3267
Revises: 292e60b94486
Create Date: 2019-07-10 14:20:23.577153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6393181f3267'
down_revision = '292e60b94486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_fin', sa.Column('date_request', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_fin', 'date_request')
    # ### end Alembic commands ###
