"""050919

Revision ID: 646b1c302c41
Revises: 06180c1a3d84
Create Date: 2019-09-05 17:26:30.344011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '646b1c302c41'
down_revision = '06180c1a3d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payment_s', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.drop_constraint('invoice_payment_s_ibfk_2', 'invoice_payment_s', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_payment_s', 'supplier', ['supplier_id'], ['id'])
    op.drop_column('invoice_payment_s', 'invoice_payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payment_s', sa.Column('invoice_payment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoice_payment_s', type_='foreignkey')
    op.create_foreign_key('invoice_payment_s_ibfk_2', 'invoice_payment_s', 'supplier', ['invoice_payment'], ['id'])
    op.drop_column('invoice_payment_s', 'supplier_id')
    # ### end Alembic commands ###
