"""pre1

Revision ID: 6a20eea66503
Revises: 60d19fff565d
Create Date: 2019-06-18 16:29:38.756017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a20eea66503'
down_revision = '60d19fff565d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_fin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llc', sa.String(length=240), nullable=True),
    sa.Column('supplier', sa.String(length=240), nullable=True),
    sa.Column('req_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('req_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_fin')
    # ### end Alembic commands ###
