"""sale

Revision ID: 6a71b4cf0300
Revises: 112386250858
Create Date: 2019-07-11 16:17:11.022685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a71b4cf0300'
down_revision = '112386250858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_fin', sa.Column('sale', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_fin', 'sale')
    # ### end Alembic commands ###
