"""0809

Revision ID: 7760ada6c1eb
Revises: 7979e1b2d0e6
Create Date: 2019-09-08 16:45:31.696368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7760ada6c1eb'
down_revision = '7979e1b2d0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_payment_s', 'commision')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payment_s', sa.Column('commision', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    # ### end Alembic commands ###
