"""0809

Revision ID: 7979e1b2d0e6
Revises: e960624d5fb8
Create Date: 2019-09-08 16:43:27.857180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7979e1b2d0e6'
down_revision = 'e960624d5fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payment_s', sa.Column('commision', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_payment_s', 'commision')
    # ### end Alembic commands ###
