"""sl

Revision ID: 79979d69d2e1
Revises: e525485f35d9
Create Date: 2019-09-29 15:54:46.993567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79979d69d2e1'
down_revision = 'e525485f35d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('cargo', sa.Text(), nullable=True))
    op.add_column('agreements', sa.Column('cnee_address', sa.Text(), nullable=True))
    op.add_column('agreements', sa.Column('cnee_name', sa.Text(), nullable=True))
    op.add_column('agreements', sa.Column('cnee_phone', sa.Text(), nullable=True))
    op.add_column('agreements', sa.Column('date_loading', sa.DateTime(), nullable=True))
    op.add_column('agreements', sa.Column('date_unloading', sa.DateTime(), nullable=True))
    op.add_column('agreements', sa.Column('shipper_address', sa.Text(), nullable=True))
    op.add_column('agreements', sa.Column('shipper_name', sa.Text(), nullable=True))
    op.add_column('agreements', sa.Column('shipper_phone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreements', 'shipper_phone')
    op.drop_column('agreements', 'shipper_name')
    op.drop_column('agreements', 'shipper_address')
    op.drop_column('agreements', 'date_unloading')
    op.drop_column('agreements', 'date_loading')
    op.drop_column('agreements', 'cnee_phone')
    op.drop_column('agreements', 'cnee_name')
    op.drop_column('agreements', 'cnee_address')
    op.drop_column('agreements', 'cargo')
    # ### end Alembic commands ###
