"""dr

Revision ID: 87f3a965eabc
Revises: 79979d69d2e1
Create Date: 2019-10-01 19:35:29.185088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f3a965eabc'
down_revision = '79979d69d2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('date_order', sa.DateTime(), nullable=True))
    op.add_column('agreements', sa.Column('driver', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreements', 'driver')
    op.drop_column('agreements', 'date_order')
    # ### end Alembic commands ###
