"""new

Revision ID: 8b0207072cb7
Revises: 
Create Date: 2019-07-16 11:38:01.472787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b0207072cb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zayvka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('pre_fin_ibfk_1', 'pre_fin', type_='foreignkey')
    op.drop_column('pre_fin', 'supplier_id')
    op.drop_column('supplier', 'deb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('deb', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pre_fin', sa.Column('supplier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('pre_fin_ibfk_1', 'pre_fin', 'supplier', ['supplier_id'], ['id'])
    op.drop_table('zayvka')
    # ### end Alembic commands ###
