"""0809

Revision ID: 8f54eb654da3
Revises: 2f0452b6f250
Create Date: 2019-09-08 16:58:12.480028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f54eb654da3'
down_revision = '2f0452b6f250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payment_s', sa.Column('cost_for_us', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_payment_s', 'cost_for_us')
    # ### end Alembic commands ###
