"""0609

Revision ID: 94570e8e484f
Revises: 99cb3b5b4ed9
Create Date: 2019-09-06 20:00:37.712888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94570e8e484f'
down_revision = '99cb3b5b4ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoicesup', sa.Column('supp_payment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoicesup', 'supp_payment', ['supp_payment_id'], ['id'])
    op.drop_column('supp_payment', 'invoice_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supp_payment', sa.Column('invoice_path', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'invoicesup', type_='foreignkey')
    op.drop_column('invoicesup', 'supp_payment_id')
    # ### end Alembic commands ###
