"""r_f

Revision ID: 960954f5c42e
Revises: 380757f1e5a1
Create Date: 2019-10-11 20:08:20.221376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960954f5c42e'
down_revision = '380757f1e5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('req_id', table_name='prefin')
    op.create_foreign_key(None, 'prefin', 'request', ['req_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prefin', type_='foreignkey')
    op.create_index('req_id', 'prefin', ['req_id'], unique=True)
    # ### end Alembic commands ###
