"""first

Revision ID: 9932d899e440
Revises: 
Create Date: 2019-07-16 21:04:04.144249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9932d899e440'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_fin', sa.Column('profit', sa.Integer(), nullable=True))
    op.add_column('pre_fin', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pre_fin', 'supplier', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pre_fin', type_='foreignkey')
    op.drop_column('pre_fin', 'supplier_id')
    op.drop_column('pre_fin', 'profit')
    # ### end Alembic commands ###
