"""dosc

Revision ID: 99344d7d5753
Revises: 14e625195511
Create Date: 2019-07-28 13:39:10.919813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99344d7d5753'
down_revision = '14e625195511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('prefin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'prefin', ['prefin_id'], ['id'])
    op.add_column('invoicecust', sa.Column('prefin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoicecust', 'prefin', ['prefin_id'], ['id'])
    op.add_column('invoicesup', sa.Column('prefin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoicesup', 'prefin', ['prefin_id'], ['id'])
    op.add_column('zayvka', sa.Column('prefin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'zayvka', 'prefin', ['prefin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zayvka', type_='foreignkey')
    op.drop_column('zayvka', 'prefin_id')
    op.drop_constraint(None, 'invoicesup', type_='foreignkey')
    op.drop_column('invoicesup', 'prefin_id')
    op.drop_constraint(None, 'invoicecust', type_='foreignkey')
    op.drop_column('invoicecust', 'prefin_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'prefin_id')
    # ### end Alembic commands ###
