"""0609

Revision ID: 99cb3b5b4ed9
Revises: 646b1c302c41
Create Date: 2019-09-06 19:53:24.433832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cb3b5b4ed9'
down_revision = '646b1c302c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supp_payment', sa.Column('invoice_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supp_payment', 'invoice_path')
    # ### end Alembic commands ###
