"""sup1

Revision ID: 9aa8b1bf3c20
Revises: d35eae553b52
Create Date: 2019-06-02 16:45:45.384621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9aa8b1bf3c20'
down_revision = 'd35eae553b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance', 'cost')
    op.add_column('supplier', sa.Column('finance', sa.Integer(), nullable=True))
    op.add_column('supplier', sa.Column('pay', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'supplier', 'paid', ['pay'], ['id'])
    op.create_foreign_key(None, 'supplier', 'finance', ['finance'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier', type_='foreignkey')
    op.drop_constraint(None, 'supplier', type_='foreignkey')
    op.drop_column('supplier', 'pay')
    op.drop_column('supplier', 'finance')
    op.add_column('finance', sa.Column('cost', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
