"""'e'

Revision ID: 9bb9b639ab4d
Revises: 
Create Date: 2019-10-23 19:03:58.376684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb9b639ab4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tr_payments', sa.Column('transit_date_recieved', sa.DateTime(), nullable=True))
    op.add_column('tr_payments', sa.Column('transit_date_send', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tr_payments', 'transit_date_send')
    op.drop_column('tr_payments', 'transit_date_recieved')
    # ### end Alembic commands ###
