"""'Supplier_pay1'

Revision ID: ab636407c04c
Revises: b82368485ca0
Create Date: 2019-08-25 14:57:27.422998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab636407c04c'
down_revision = 'b82368485ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supp_payment', sa.Column('tora_red', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supp_payment', 'tora_red')
    # ### end Alembic commands ###
