"""'transit_status'

Revision ID: acca149ab211
Revises: da4c53717f19
Create Date: 2019-10-15 20:32:10.518608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acca149ab211'
down_revision = 'da4c53717f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transit', sa.Column('status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transit', 'status')
    # ### end Alembic commands ###
