"""'31083'

Revision ID: ad4cd0b383e3
Revises: b17182538f9f
Create Date: 2019-08-31 16:20:00.743485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4cd0b383e3'
down_revision = 'b17182538f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoicesup', sa.Column('supp_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoicesup', 'supplier', ['supp_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoicesup', type_='foreignkey')
    op.drop_column('invoicesup', 'supp_id')
    # ### end Alembic commands ###
