"""31082

Revision ID: b17182538f9f
Revises: 494d49516402
Create Date: 2019-08-31 15:49:52.999421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17182538f9f'
down_revision = '494d49516402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoicesup', sa.Column('req_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoicesup', 'request', ['req_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoicesup', type_='foreignkey')
    op.drop_column('invoicesup', 'req_id')
    # ### end Alembic commands ###
