"""'Supplier_pay1'

Revision ID: b82368485ca0
Revises: f9694a00e660
Create Date: 2019-08-25 14:53:09.100975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82368485ca0'
down_revision = 'f9694a00e660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supp_payment', sa.Column('bank', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supp_payment', 'bank')
    # ### end Alembic commands ###
