"""cust

Revision ID: b9af47a09df9
Revises: 961d830a009c
Create Date: 2019-09-16 20:49:07.359617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9af47a09df9'
down_revision = '961d830a009c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payment_c', sa.Column('invoice_number', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_payment_c', 'invoice_number')
    # ### end Alembic commands ###
