"""n

Revision ID: bc7af55d47ca
Revises: e334515242ba
Create Date: 2019-10-23 15:07:29.254485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7af55d47ca'
down_revision = 'e334515242ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tr_payments', sa.Column('transit_date_recieved', sa.DateTime(), nullable=True))
    op.add_column('tr_payments', sa.Column('transit_date_send', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tr_payments', 'transit_date_send')
    op.drop_column('tr_payments', 'transit_date_recieved')
    # ### end Alembic commands ###
