"""date_to

Revision ID: bd6e7d2a43c7
Revises: 237ee7063a80
Create Date: 2019-07-25 19:00:31.576489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6e7d2a43c7'
down_revision = '237ee7063a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prefin', sa.Column('s_inv_date_to_pay', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prefin', 's_inv_date_to_pay')
    # ### end Alembic commands ###
