"""'fio'

Revision ID: c216aeedc91b
Revises: c399b9eafdfb
Create Date: 2019-02-21 10:18:11.081093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c216aeedc91b'
down_revision = 'c399b9eafdfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('external', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('fio', sa.String(length=240), nullable=True))
    op.add_column('user', sa.Column('mobile', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('start_work', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'start_work')
    op.drop_column('user', 'mobile')
    op.drop_column('user', 'fio')
    op.drop_column('user', 'external')
    # ### end Alembic commands ###
