"""'dogovor_z'

Revision ID: c399b9eafdfb
Revises: 93fa63d7dd77
Create Date: 2019-02-18 17:07:06.761664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c399b9eafdfb'
down_revision = '93fa63d7dd77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('dogovor_zayavka', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'dogovor_zayavka')
    # ### end Alembic commands ###
