"""vat

Revision ID: c3e17cb5f703
Revises: 9932d899e440
Create Date: 2019-07-16 22:01:34.982127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e17cb5f703'
down_revision = '9932d899e440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_fin', sa.Column('vat', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_fin', 'vat')
    # ### end Alembic commands ###
