"""new

Revision ID: c576f2240186
Revises: 8d7cd2859161
Create Date: 2019-10-24 07:29:24.026955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c576f2240186'
down_revision = '8d7cd2859161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tr_payments', sa.Column('doc_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tr_payments', 'doc_path')
    # ### end Alembic commands ###
