"""t

Revision ID: c61cbf31c947
Revises: 99344d7d5753
Create Date: 2019-07-31 23:40:33.951192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61cbf31c947'
down_revision = '99344d7d5753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('req_id', sa.Integer(), nullable=True),
    sa.Column('prefin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prefin_id'], ['prefin.id'], ),
    sa.ForeignKeyConstraint(['req_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tn')
    # ### end Alembic commands ###
