"""0809

Revision ID: c9252ea56eb7
Revises: df5d1e777502
Create Date: 2019-09-08 16:37:04.095918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9252ea56eb7'
down_revision = 'df5d1e777502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payment_s', sa.Column('commision', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_payment_s', 'commision')
    # ### end Alembic commands ###
