"""invoicepaymnet

Revision ID: ca001e29316b
Revises: ad4cd0b383e3
Create Date: 2019-09-02 07:37:15.834934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca001e29316b'
down_revision = 'ad4cd0b383e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_payment_s',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_inv_number', sa.String(length=120), nullable=True),
    sa.Column('summ_pay', sa.Integer(), nullable=True),
    sa.Column('transit', sa.String(length=120), nullable=True),
    sa.Column('date_payment', sa.DateTime(), nullable=True),
    sa.Column('supp_payment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supp_payment'], ['supp_payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_payment_s')
    # ### end Alembic commands ###
