"""'inn'

Revision ID: cbb0863c2f81
Revises: c216aeedc91b
Create Date: 2019-02-21 13:28:40.982973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb0863c2f81'
down_revision = 'c216aeedc91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('inn', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'customer', ['inn'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_column('customer', 'inn')
    # ### end Alembic commands ###
