"""'new'

Revision ID: d24267507e59
Revises: 2ce41f7fd958
Create Date: 2019-10-18 19:41:58.305157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24267507e59'
down_revision = '2ce41f7fd958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tr_payments', sa.Column('status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tr_payments', 'status')
    # ### end Alembic commands ###
