"""r_f

Revision ID: da4c53717f19
Revises: 960954f5c42e
Create Date: 2019-10-11 20:09:27.399021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4c53717f19'
down_revision = '960954f5c42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prefin', sa.Column('request_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'prefin', ['req_id'])
    op.drop_constraint('prefin_ibfk_2', 'prefin', type_='foreignkey')
    op.create_foreign_key(None, 'prefin', 'request', ['request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prefin', type_='foreignkey')
    op.create_foreign_key('prefin_ibfk_2', 'prefin', 'request', ['req_id'], ['id'])
    op.drop_constraint(None, 'prefin', type_='unique')
    op.drop_column('prefin', 'request_id')
    # ### end Alembic commands ###
