"""m-t-m-s-f

Revision ID: df694b4fa28a
Revises: ca001e29316b
Create Date: 2019-09-05 04:29:14.502952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df694b4fa28a'
down_revision = 'ca001e29316b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finsup',
    sa.Column('prefin_id', sa.Integer(), nullable=True),
    sa.Column('supp_ip', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prefin_id'], ['prefin.id'], ),
    sa.ForeignKeyConstraint(['supp_ip'], ['supplier.id'], )
    )
    op.drop_column('prefin', 's_inv_part_payment_25wk_2019')
    op.drop_column('prefin', 's_inv_part_payment_24wk_2019')
    op.drop_column('prefin', 's_inv_part_payment_20wk_2019')
    op.drop_column('prefin', 's_inv_part_payment_22wk_2019')
    op.drop_column('prefin', 's_inv_part_payment_27wk_2019')
    op.drop_column('prefin', 's_inv_part_payment_17wk')
    op.drop_column('prefin', 's_inv_part_payment_26wk_2019')
    op.drop_column('prefin', 's_inv_part_payment_23wk_2019')
    op.drop_column('prefin', 's_inv_part_payment_21wk_2019')
    op.drop_column('prefin', 's_inv_part_payment_28wk_2019')
    op.drop_column('prefin', 's_inv_part_payment_18wk_2019')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prefin', sa.Column('s_inv_part_payment_18wk_2019', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('prefin', sa.Column('s_inv_part_payment_28wk_2019', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('prefin', sa.Column('s_inv_part_payment_21wk_2019', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('prefin', sa.Column('s_inv_part_payment_23wk_2019', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('prefin', sa.Column('s_inv_part_payment_26wk_2019', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('prefin', sa.Column('s_inv_part_payment_17wk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('prefin', sa.Column('s_inv_part_payment_27wk_2019', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('prefin', sa.Column('s_inv_part_payment_22wk_2019', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('prefin', sa.Column('s_inv_part_payment_20wk_2019', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('prefin', sa.Column('s_inv_part_payment_24wk_2019', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('prefin', sa.Column('s_inv_part_payment_25wk_2019', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('finsup')
    # ### end Alembic commands ###
