"""re_m

Revision ID: dfae85d42c94
Revises: 6393181f3267
Create Date: 2019-07-10 15:52:24.668045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfae85d42c94'
down_revision = '6393181f3267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_fin', sa.Column('complete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_fin', 'complete')
    # ### end Alembic commands ###
