"""'n'

Revision ID: e334515242ba
Revises: 
Create Date: 2019-10-23 09:37:40.488340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e334515242ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ccoments')
    op.add_column('request', sa.Column('complete_fin', sa.Integer(), nullable=True))
    op.add_column('request', sa.Column('test_new', sa.Integer(), nullable=True))
    op.add_column('supplier', sa.Column('finance', sa.Integer(), nullable=True))
    op.add_column('supplier', sa.Column('pay', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'supplier', 'finance', ['finance'], ['id'])
    op.create_foreign_key(None, 'supplier', 'paid', ['pay'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier', type_='foreignkey')
    op.drop_constraint(None, 'supplier', type_='foreignkey')
    op.drop_column('supplier', 'pay')
    op.drop_column('supplier', 'finance')
    op.drop_column('request', 'test_new')
    op.drop_column('request', 'complete_fin')
    op.create_table('ccoments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='ccoments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
