"""first

Revision ID: e3780a79621d
Revises: 
Create Date: 2019-07-12 15:25:14.356951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3780a79621d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_fin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llc', sa.String(length=240), nullable=True),
    sa.Column('supplier', sa.String(length=240), nullable=True),
    sa.Column('req_id', sa.Integer(), nullable=True),
    sa.Column('date_request', sa.DateTime(), nullable=True),
    sa.Column('complete', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=240), nullable=True),
    sa.Column('sale', sa.String(length=240), nullable=True),
    sa.Column('status', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('req_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_fin')
    # ### end Alembic commands ###
