"""g

Revision ID: e525485f35d9
Revises: d26fc898e1d5
Create Date: 2019-09-24 18:57:08.662497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e525485f35d9'
down_revision = 'd26fc898e1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreements', 'path')
    # ### end Alembic commands ###
