"""0809

Revision ID: e960624d5fb8
Revises: c9252ea56eb7
Create Date: 2019-09-08 16:43:03.851097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e960624d5fb8'
down_revision = 'c9252ea56eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_payment_s', 'commision')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payment_s', sa.Column('commision', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
