"""'2908'

Revision ID: f47c4dbec479
Revises: 434a0a3742a1
Create Date: 2019-08-29 20:30:36.377444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47c4dbec479'
down_revision = '434a0a3742a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supp_payment', sa.Column('fin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'supp_payment', 'prefin', ['fin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supp_payment', type_='foreignkey')
    op.drop_column('supp_payment', 'fin_id')
    # ### end Alembic commands ###
