"""tr

Revision ID: f891e393d4da
Revises: f1a28d83034f
Create Date: 2019-10-17 19:58:26.043838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f891e393d4da'
down_revision = 'f1a28d83034f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tr_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=True),
    sa.Column('transit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transit_id'], ['transit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tr_payments')
    # ### end Alembic commands ###
