"""'Supplier_pay'

Revision ID: f9694a00e660
Revises: 
Create Date: 2019-08-25 14:41:24.612571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9694a00e660'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supp_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_inv_number', sa.String(length=120), nullable=True),
    sa.Column('c_invoice_date', sa.DateTime(), nullable=True),
    sa.Column('c_inv_amount', sa.Integer(), nullable=True),
    sa.Column('c_inv_currency', sa.String(length=120), nullable=True),
    sa.Column('c_inv_pay_day', sa.DateTime(), nullable=True),
    sa.Column('c_payment_summ', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('inn', table_name='supplier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('inn', 'supplier', ['inn'], unique=True)
    op.drop_table('supp_payment')
    # ### end Alembic commands ###
